// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6BMVKej07BCgxc7MpC-v66-iOcmfffPo',
    appId: '1:783801096019:web:673091e02a7758e73373a6',
    messagingSenderId: '783801096019',
    projectId: 'travelbuddy-aaad2',
    authDomain: 'travelbuddy-aaad2.firebaseapp.com',
    storageBucket: 'travelbuddy-aaad2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASoj_JV_yBuV7TAebusjgqh2loN6rHidA',
    appId: '1:783801096019:android:20306853a1d6628b3373a6',
    messagingSenderId: '783801096019',
    projectId: 'travelbuddy-aaad2',
    storageBucket: 'travelbuddy-aaad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3sYQK6cbPG6-3Wm_EVpni9SzwvVi7CAQ',
    appId: '1:783801096019:ios:d65b2b5fdc7e3d1b3373a6',
    messagingSenderId: '783801096019',
    projectId: 'travelbuddy-aaad2',
    storageBucket: 'travelbuddy-aaad2.firebasestorage.app',
    iosBundleId: 'com.example.travelbuddyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3sYQK6cbPG6-3Wm_EVpni9SzwvVi7CAQ',
    appId: '1:783801096019:ios:d65b2b5fdc7e3d1b3373a6',
    messagingSenderId: '783801096019',
    projectId: 'travelbuddy-aaad2',
    storageBucket: 'travelbuddy-aaad2.firebasestorage.app',
    iosBundleId: 'com.example.travelbuddyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6BMVKej07BCgxc7MpC-v66-iOcmfffPo',
    appId: '1:783801096019:web:cf73991e0e287d213373a6',
    messagingSenderId: '783801096019',
    projectId: 'travelbuddy-aaad2',
    authDomain: 'travelbuddy-aaad2.firebaseapp.com',
    storageBucket: 'travelbuddy-aaad2.firebasestorage.app',
  );
}
