# ios/Podfile

platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

flutter_application_path = File.expand_path('../..', __FILE__)
load File.join(flutter_application_path, '.flutter-plugins-dependencies')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
