default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      export_team_id: "Y9GHGBP8U6", # Falls nötig
      skip_codesigning: false
    )

    upload_to_testflight
  end
end
