default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :beta do
    build_app(
      scheme: "Runner",
      export_method: "app-store",
      allow_provisioning_updates: true
    )

    upload_to_testflight
  end
end
